use anyhow::Result;
use async_trait::async_trait;

use super::Event;

/// Trait to handle events generated by solo machine
#[async_trait]
pub trait EventHandler: Sync + Send {
    /// Handles an event
    async fn handle(&self, event: Event) -> Result<()>;
}

/// Trait to register different event handlers
pub trait HandlerRegistrar: EventHandler {
    /// Registers a new event handler
    fn register(&mut self, handler: Box<dyn EventHandler>);
}
