CREATE TABLE IF NOT EXISTS chain_keys (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    chain_id TEXT NOT NULL,
    public_key TEXT NOT NULL,
    created_at TIMESTAMPZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(chain_id, public_key)
);

