CREATE TABLE IF NOT EXISTS chains (
    id TEXT PRIMARY KEY NOT NULL,
    node_id TEXT NOT NULL,
    config JSONB NOT NULL,
    consensus_timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sequence BIGINT NOT NULL DEFAULT 1,
    packet_sequence BIGINT NOT NULL DEFAULT 1,
    connection_details JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
